### ISSUE TITLE
HTTP Error 403, client error , forbidden url

### ISSUE THREAD

**Issue by mlwbd** [xob0t/gphotos_mobile_client#1]

**Comment by pgajeelh** [comment]
Having the same issue here, tried 3 different auth_data. I'm thinking I may have hit Google's limit by increasing the threads.

**Comment by manootje** [comment]
Having the same issue. @pgajeelh did you manage to fix it?

**Comment by pgajeelh** [comment]
No. I continue using Vanced on my other Android phones.
